services:
  pg_test:
    image: bitnami/postgresql:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=brevly_test
    volumes:
      - ./docker_test:/docker-entrypoint-initdb.d